### ISSUE TITLE
Cannot run the demo

### ISSUE THREAD

**Issue by vndzung** [jgrandja/oauth2-protocol-patterns#1]
Hi,

Thank for sharing the demo!

When I access localhost:8080, after a while it will show FAILURE. 
And when I see the uaa-server.log, I have an error:  

`Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException`

I try to add these dependencies but it doesn't work

```
dependencies {
    uaa("org.cloudfoundry.identity:cloudfoundry-identity-uaa:${uaaVersion}@war") {
        artifact {
            name = "cloudfoundry-identity-uaa"
            extension = 'war'
            type = 'war'
        }

        compile "javax.xml.bind:jaxb-api:2.2.11"
        compile "com.sun.xml.bind:jaxb-core:2.2.11"
        compile "com.sun.xml.bind:jaxb-impl:2.2.11"
        compile "javax.activation:activation:1.1.1"
    }
}
```

Can you help me on this?

**Comment by asaikali** [comment]
Looks like you are trying to run this on Java 11, please try with Java 8 JDK. I think the UAA dependencies are not compatible with Java 11 yet.

**Comment by vndzung** [comment]
I am using Java 11. Thanks for your response!
