### ISSUE TITLE
How to implement Client Assertion with Spring Security 5.2+ ? 

### ISSUE THREAD

**Issue by wiliao** [jgrandja/oauth2-protocol-patterns#10]
Hi Joe,

Can you please advise how to implement Client Assertion with Spring Security 5.2+ ? 

Thank you in advance,
Will

**Comment by jgrandja** [comment]
@wiliao I responded [here](https://github.com/jgrandja/oauth2-protocol-patterns/issues/9#issuecomment-842390157)
