### ISSUE TITLE
Which SSO provider to use : Spring or Keycloak ?

### ISSUE THREAD

**Issue by kpcsuh** [jgrandja/oauth2-protocol-patterns#7]
Thank you Joe, for this great sample application demo. 

Question: I am try to decide which provider to use (spring or keycloak) for my SSO application. Can you guide me to right direction. We are planning to starting SSO  development in couple of weeks. 

https://github.com/jgrandja/oauth2-protocol-patterns/blob/12567fb6d09ce6a81670a532009c7ab0b41ca5a5/ui-app/src/main/resources/application.yml#L28

**Comment by jgrandja** [comment]
@kpcsuh Spring Authorization Server is still in early development stage. We're targeting an MVP release the 2nd half of 2021.

I can't really recommend a provider for you to use. That is really a decision you and your team will need to make. I can say that I favour Okta and curity.io
