### ISSUE TITLE
How does Spring Security 5.2 and later support Client Assertion?

### ISSUE THREAD

**Issue by wiliao** [jgrandja/oauth2-protocol-patterns#9]
Hi Joe,

Can you please provide an example about how to implement Client Assertion (one kind of client credentials for service to service) with Spring Security 5.2 and above?

Thank you in advance,
Will

**Comment by jgrandja** [comment]
Hi Will,

JWT Client Authentication was just added in 5.5, which is being released today.

Here is a link to the snapshot reference on how to configure.

https://docs.spring.io/spring-security/site/docs/5.5.0-SNAPSHOT/reference/html5/#oauth2Client-client-auth-support

**Comment by wiliao** [comment]
Thanks Joe, just saw your comment.
